[#patterns-retry]
== Retrying in the event of a temporary failure

__Goal__::

* The <<reference#reference-retry,retry>> operator can be included in a pipeline to retry a subscription when a `.failure` completion occurs.

__References__::

* <<reference#reference-catch,catch>>
* <<reference#reference-retry,retry>>
* <<reference#reference-delay,delay>>
* <<reference#reference-trymap,tryMap>>

__See also__::

* <<patterns#patterns-oneshot-error-handling,Using catch to handle errors in a one-shot pipeline>>
* <<patterns#patterns-continual-error-handling,Using flatMap with catch to handle errors>>

__Code and explanation__::

When requesting data from a dataTaskPublisher, there is always the possibility that the request may fail, and instead of data you may receive a `.failure` completion with an error.
The <<reference#reference-retry,retry>> operator will let you retry that same request for a set number of attempts that you specify.
The retry operator works by ignoring and passing through any data values, only reacting within the chain when a `.failure` completion is sent.
In that case, it will retry the subscription to the same publisher.

The <<reference#reference-retry,retry>> operator is commonly desired when attempting to request network resources with an unstable connection, or other situations where the answer might change if the request happens again after a short period of time.
If the number of retries specified all fail, then the `.failure` completion is passed down to the subscriber of this operator.

In our example below, we are using retry in combination with a <<reference#reference-delay,delay>> operator.
The delay operator puts a small random delay in how long the request takes, and is really most useful when the retry operator triggers.
This spaces out the retry attempts, so that the retries don't all happen in quick succession.

This example also includes the use of the <<reference#reference-trymap,tryMap>> operator to more fully inspect any URLResponse from the publisher.
Any response from the server is encapsaulted by URLSession, and passed forward as a valid response.
Because of this, URLSession doesn't treat a 404 Not Found http response as an error response.
Using tryMap lets us inspect the response code that was sent, and verify that it was a 200 response code.
In this example, if the response code is anything but a 200 response, it throws an exception - which in turn causes the tryMap operator to pass down a `.failure` response rather than data.
This example sets the tryMap *after* the retry operator so that retry will only re-attempt the request when the site didn't respond.

[source, swift]
----
let remoteDataPublisher = urlSession.dataTaskPublisher(for: self.mockURL!)
    .delay(for: DispatchQueue.SchedulerTimeType.Stride(integerLiteral: Int.random(in: 1..<5)), scheduler: backgroundQueue) <1>
    .retry(3) <2>
    .tryMap { data, response -> Data in <3>
        guard let httpResponse = response as? HTTPURLResponse,
            httpResponse.statusCode == 200 else {
                throw TestFailureCondition.invalidServerResponse
        }
        return data
    }
    .decode(type: PostmanEchoTimeStampCheckResponse.self, decoder: JSONDecoder())
    .subscribe(on: backgroundQueue)
    .eraseToAnyPublisher()
----

<1> The <<reference#reference-delay,delay>> operator will hold the results flowing through the pipeline for a short duration, in this case for a random selection of 1 to 5 seconds. By adding delay here in the pipeline, it will always occur, even if the original request is successful.
<2> Retry is specified as trying 3 times.
<3> tryMap is being used to inspect the data result from dataTaskPublisher and return a `.failure` completion if the response from the server is valid, but not a 200 HTTP response code.

[WARNING]
====
When using the <<reference#reference-retry,retry>> operator with <<reference#reference-datataskpublisher,URLSession.dataTaskPublisher>>, verify that the URL you are requesting isn't going to have negative side effects if requested repeatedly or with a retry.
Ideally such requests are be expected to be idempotent.
If they are not, the <<reference#reference-retry,retry>> operator may make multiple requests, with very unexpected side effects.
====

// force a page break - in HTML rendering is just a <HR>
<<<
'''
